### PR TITLE
Improve cluster retries

### PR DESCRIPTION
**Pull request by jaymell**
Currently we don't sleep for certain classes of errors, which in my testing leads to certain potentially suboptimal results. Most notably, `MOVED` errors are likely to be thrown when a cluster is in an unhealthy state, such as during a node loss. With our current strategy of immediately retrying `MOVED` errors without pause, we eliminate the client's ability to recover in many scenarios.

In any case, I think it's reasonable that we sleep for all retryable errors.

Relates to #906.

### CODE REVIEW

**Comment by jaymell** [comment]
Comparisons between this branch and main in a few different scenarios (apologies for the formatting, but I think the results are clear). This is based on running a simple `SET` command in a loop, similar to the scenario presented in #906.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
</head>

<body>


Scenario | Branch | Error log | Time to recover
-- | -- | -- | --
Node completely lost (shut down primary node, `docker stop -t0 $CONTAINER_ID`) | main | Request error Connection reset by peer (os error 104), IoErrorRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedError: An error was signalled by the server - Moved: 6918 172.20.0.4:6379 | N/A
Node completely lost (shut down primary node, `docker stop -t0 $CONTAINER_ID`) | jaymell/better-retry | Request error Connection reset by peer (os error 104), IoErrorRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, Moved | 72.5 seconds
Node stopped for 3 seconds; restarted | main | Request error broken pipe, IoErrorRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedError: An error was signalled by the server - Moved: 6918 172.20.0.4:6379 | N/A
Node stopped for 3 seconds; restarted | jaymell/better-retry | Request error broken pipe, IoErrorRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - ClusterDown: The cluster is down, ClusterDown | 6.9 seconds
Node restarted (`docker restart $CONTAINER_ID`) | main | Request error broken pipe, IoErrorRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedRequest error An error was signalled by the server - Moved: 6918 172.20.0.4:6379, MovedError: An error was signalled by the server - Moved: 6918 172.20.0.4:6379 | N/A
Node restarted (`docker restart $CONTAINER_ID`) | jaymell/better-retry | Request error broken pipe, IoErrorRequest error An error was signalled by the server - ClusterDown: The cluster is down, ClusterDownRequest error An error was signalled by the server - ClusterDown: The cluster is down, ClusterDown | 3.8 seconds


</body>

</html>

**Comment by nihohit** [comment]
the logs are from the caller?
and do you have any idea why does the connection in master never recover? the sleep should affect individual requests, but this implies that this change modifies the whole cluster recovery/topology refresh process.

**Comment by jaymell** [comment]
> the logs are from the caller?

Correct, basically a slightly modified output of the current TRACE log we currently have when we receive a response error:

> and do you have any idea why does the connection in master never recover? 

By "connection in master" do you mean the request in the main branch, or literally the connection to the master slot? If the former, it's because retries are exhausted before the cluster heals itself. If the latter, it's because the sockets are closed when the node is restarted or shut down. 

> the sleep should affect individual requests, but this implies that this change modifies the whole cluster recovery/topology refresh process.

Yes, that's a bit sloppy here. I'm not immediately sure how to untangle the request sleeps/retries from the connection-state recovery. Let me have a think on it.

**Comment by jaymell** [comment]
Closing in favor of #968

**Pull request closed without merging**
