### PR TITLE
moved the implement macro to allow for multiple calls of it in separate files

### PR DESCRIPTION
**Pull request by d3rpp**
Relating to step one of #650

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
LGTM, thanks for splitting it out!

**Comment by d3rpp** [comment]
Once this is done ill open up step 2, because I've been working on it all day

**Comment by d3rpp** [comment]
@djc if at all possible could you please merge these changes at your earlier convenience so I can put up the second PR?

**Comment by djc** [comment]
Given that @jaymell more or less approved the previous one, I guess we can merge this one without his approval.

**Pull request merged**
