### PR TITLE
Make Direction a public enum to use with Commands like `blmove` (#646)

### PR DESCRIPTION
**Pull request by rudolphfroger-ds**
Cherry-picked from the main branch

### CODE REVIEW

**Comment by djc** [comment]
Looks like CI is not running for this branch. Will need to merge #676 and then push this branch again.

**Comment by djc** [comment]
Can you push again trigger CI?

**Comment by jaymell** [comment]
I just realized the workflow changes weren't actually brought into this branch :neutral_face:

**Comment by djc** [comment]
> I just realized the workflow changes weren't actually brought into this branch :neutral_face: 

I was under the impression they wouldn't need to be? But might be wrong about that.

**Pull request merged**
