### PR TITLE
Tls sec

### PR DESCRIPTION
**Pull request by nonirosenfeldredis**

### CODE REVIEW

**Comment by nonirosenfeldredis** [comment]
woohoo! I added support for MTLS. [mtls issue](https://github.com/redis-rs/redis-rs/issues/393)
u can configure from client your CA certificate and identity ( client cert & its private key)

**Comment by nonirosenfeldredis** [comment]
we already use this code in our redis-rs fork in our RUST module within redis.

**Comment by jaymell** [comment]
Hi, thanks for the PR. Can you clean up the commit history here? (Possibly by adding your changes to a new branch taken off main)

**Comment by nonirosenfeldredis** [comment]
opened a clean PR instead: 

[https://github.com/redis-rs/redis-rs/pull/792]

**Pull request closed without merging**
