### PR TITLE
Fix XREADGROUP command ordering as per Redis Docs, and compatibility with Upstash Redis

### PR DESCRIPTION
**Pull request by prabhpreet**
Fixes https://github.com/redis-rs/redis-rs/issues/959

Ordering also reported with Upstash Redis: https://github.com/upstash/issues/issues/74

### CODE REVIEW

**Comment by nihohit** [comment]
@prabhpreet thanks!
can you please add a test?

**Comment by prabhpreet** [comment]
@nihohit I've updated the command order in the tests which had specified the other ordering before, and passes.

There should be additional tests with Upstash Redis if @upstash could provide an Redis instance for test CI, but I'd suggest it be a separate PR due to adding support to test against a non localhost remote server, and the likeliness other commands will also come up with similar ordering issues.

**Comment by nihohit** [comment]
https://github.com/redis-rs/redis-rs/blob/2718fdd8f466bbc70e928a7026dbad8fbd03824d/redis/src/commands/mod.rs#L1763
this doc also needs to be fixed

I see that there are tests running XREADGROUP, so there's no need to anything else AFAIS.

**Review by nihohit — APPROVED** [review]

**Comment by prabhpreet** [comment]
Not sure why Rust / build (7.2.0, nightly) fails for `test_async_cluster_basic_cmd` in https://github.com/prabhpreet/redis-rs/blob/43b39087ea196febcfc0d007af14e3d3ac92c163/redis/tests/test_cluster_async.rs#L24

**Comment by nihohit** [comment]
@prabhpreet lint still broken.

**Comment by nihohit** [comment]
Thanks for the fix @prabhpreet !

**Comment by prabhpreet** [comment]
@nihohit Thanks for the review and approval. Can this be published into a release? When are new releases cut for cargo?

**Comment by nihohit** [comment]
I'm not sure when will we make the new release. If you need the feature, you can use the crate from a git commit instead of from crates.io.

**Pull request merged**
