### PR TITLE
[5/5] Add Async MultiplexedClusterConnection

### LINKED ISSUE #421: is there support for async commands under cluster connection?

### PR DESCRIPTION
**Pull request by utkarshgupta137**
Fixes #421.

This is the final PR for adding async connection support for cluster.

TODO:
- [ ] Add tests
- [ ] Add retry support
- [ ] Add reconnect support
- [ ] Profile & improve performance
- [ ] Benchmark against other implementations (redis_cluster_async & fred.rs)
- [ ] Add/improve docs

P.S. I've not added support for `simple` async connections, only `multiplexed` connections. I'm unaware of any benefits of the `simple` async connections.

### CODE REVIEW

**Comment by utkarshgupta137** [comment]
@djc Can you do an initial review of these changes, after that I can proceed with adding tests/docs etc.

**Comment by utkarshgupta137** [comment]
@djc @jaymell I've rebased this PR onto main. Now we've 3 commits, each of which I think should be separated into individual PRs, after some initial reviews here. I'm not sure how I can further break down the 3 commits & also get it passing tests at the same time.
I would recommend you hide whitespace changes & then review each commit. I'll try to see if I can sub-divide the commits this weekend, but I doubt it would make the review much more straightforward. I think it would be helpful if we could connect over discord or something so we can discuss changes in a rapid-fire manner.

**Comment by djc** [comment]
We have a Discord channel here: https://discord.gg/WHKcJK9AKP.

**Comment by jaymell** [comment]
I just want to second @djc's request that we significantly break these changes down into smaller commits. The work looks promising, but we need to be very careful about lumping so many unrelated changes together.

**Comment by utkarshgupta137** [comment]
@jaymell @djc Raised a PR with the first commit broken up: #653. Once that is merged, I can start working on the next one.

**Comment by utkarshgupta137** [comment]
@jaymell @djc Raised a PR with the first commit broken up: #654. Now this PR only contains changes related to adding Async MultiplexedClusterConnection

**Comment by neogenie** [comment]
Hi @djc @jaymell @utkarshgupta137

**Comment by djc** [comment]
See #653.

**Comment by utkarshgupta137** [comment]
Depends on #654

**Comment by nihohit** [comment]
@utkarshgupta137
Hi,
I see that you have multiple PRs for improving the cluster connection, that are based on old versions of the cluster. Are you interested in rebasing them, or can they be closed?

**Comment by jaymell** [comment]
Closing, longer relevant given subsequent work.

**Pull request closed without merging**
