### PR TITLE
Create an `r2d2` example.

### PR DESCRIPTION
**Pull request by ibraheemdev**
The `r2d2-redis` crate is pretty popular, and the functionality it provides is already included in this crate with the `r2d2` module. 

The docs are pretty fuzzy. There is currently no documentation regarding how to use r2d2 with this crate other than:

> To open a connection you need to create a client and then to fetch a connection from it. In the future there will be a connection pool for those, currently each connection is separate and not pooled.

See #385 as well.

### CODE REVIEW

**Comment by invis87** [comment]
Is there are a way to use `use redis::AsyncCommands;` with r2d2?

**Comment by ibraheemdev** [comment]
@invis87 No. r2d2 is a synchronous connection pool crate. To use `redis::AsyncCommands`, look into [`deadpool-redis`](https://crates.io/crates/deadpool-redis) or [`bb8-redis`](https://crates.io/crates/bb8-redis/0.3.1)

**Comment by Marwes** [comment]
I'd recommend just using the `MultiplexedConnection` for async as it can already be cloned. Connection pooling is only necessary in some really specifica schenarios.

**Comment by ibraheemdev** [comment]
@Marwes Well, considering `r2d2-redis` has over 90k downloads, and this functionality already exists within this crate, I think the added documentation and examples wouldn't hurt.

**Comment by Marwes** [comment]
The PR is good, I was just commenting on using pooling for async connections, in which case it is unnecessary in most cases.

**Comment by weihanglo** [comment]
Add an `[[example]]` item into Cargo.toml would be great!

```toml
[[example]]
name = "r2d2"
required-features = ["r2d2"]
```

**Comment by jasongoodwin** [comment]
It's really hard to find this info, the readme specifically says that the pooling feature doesn't exist. This needs to get merges, maybe reference using pipe with deref too eg 

let res: redis::RedisResult<Vec<i32>> = pipe.query(conn.deref_mut());

**Comment by ibraheemdev** [comment]
Btw `pipe.query(conn.deref_mut())` is just `pipe.query(&mut *conn)`.

**Comment by ibraheemdev** [comment]
@Marwes can this be merged if you have write access?

**Comment by ibraheemdev** [comment]
Also regarding the async point, I think pooling is important for async web servers, which is a common use case.

**Comment by Marwes** [comment]
> Also regarding the async point, I think pooling is important for async web servers, which is a common use case.

It usually isn't necessary if you use the multiplexed connection as that will let you send multiple concurrent requests to redis anyway. (Since redis is single threaded, or at least mostly so, having all requests on the same stream makes little difference as they become serialized in the redis server anyway).

**Comment by Parth** [comment]
@Marwes regarding the suitability for `MultiplexedConnection` in the context of an "async web server":

`MultiplexedConnection` doesn't support transactions, right? [StackExchange.redis](https://stackexchange.github.io/StackExchange.Redis/Transactions.html#and-in-stackexchangeredis) gives multiplexed transactions some special treatment that I'm not sure this crate does. I was going to whip up an example similar to #254, but my basic attempt didn't really get off the ground:

```rust
    let mut conn = redis::Client::open("redis://127.0.0.1:6379")?
        .get_multiplexed_tokio_connection()
        .await?;

    redis::transaction(&mut conn, &["hello"], |conn, pipe| Ok(Some(())))?;
```

returns: 

```
error[E0277]: the trait bound `MultiplexedConnection: redis::ConnectionLike` is not satisfied
    --> src/main.rs:20:24
     |
20   |     redis::transaction(&mut conn, &["hello"], |conn, pipe| Ok(Some(())))?;
     |                        ^^^^^^^^^ the trait `redis::ConnectionLike` is not implemented for `MultiplexedConnection`
     | 
    ::: /Users/parthmehrotra/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.21.4/src/connection.rs:1080:8
     |
1080 |     C: ConnectionLike,
     |        -------------- required by this bound in `transaction`

For more information about this error, try `rustc --explain E0277`.
warning: `redis-test` (bin "redis-test") generated 1 warning
error: could not compile `redis-test` due to previous error; 1 warning emitted
```

Error message a bit confusing, but after some digging [`ConnectionLike`](https://docs.rs/redis/latest/redis/aio/struct.MultiplexedConnection.html#impl-ConnectionLike) != [`ConnectionLike`](https://docs.rs/redis/latest/redis/aio/trait.ConnectionLike.html).

And so I sought out `async` ways to do transactions, and stumbled upon: #353. Dropping in that macro and watching a key in a `cloned`, and sure enough this lets me create transactions with a cloned `MultiplexedConnection`, but, naturally, they don't behave the way you'd expect them too, transactions across cloned `MultiplexedConnection`s step on each other, unwatching each-other's keys.

So ultimately I'm trying to figure out:

> Connection pooling is only necessary in some really specifica schenarios.

Is the whole family of doing `async` transactions one of these specific scenarios, or am I just doing something wrong?

**Comment by Marwes** [comment]
> Is the whole family of doing async transactions one of these specific scenarios, or am I just doing something wrong?

Yes, `MultiplexedConnection` assumes that each command run on it is independentent so you do not manually want to start a transaction (but using https://docs.rs/redis/0.21.4/redis/struct.Pipeline.html works)

**Comment by Parth** [comment]
I agree `Pipeline` will work as expected, but the `WATCH`s associated with competing pipelines will not work as expected. They're going to `UNWATCH` each other's keys. Which, imo, makes `pipe().atomic()` less useful for most people.

Other crates, for example [StackExchange.Redis](https://stackexchange.github.io/StackExchange.Redis/Transactions.html#and-in-stackexchangeredis) give this stuff special treatment.

I think for people trying to do the `async web-server redis` + `transactions` they need to seek out `bb8` or `deadpool` (which is fine, because both those projects have pretty well documented examples).

But I think what we should add to this crate, is an `async` variant of `redis::transaction`. I'm struggling a bit with the lifetimes associated with that stuff, but if I'm able to sort it out, would that sort of contribution be welcome in this crate?

**Comment by rudolfolah** [comment]
This PR is great, I was able to get the example working with `actix-web`: https://github.com/actix/examples/issues/569

Thanks!

**Comment by jaymell** [comment]
Hmm... I'm looking back on this and am unclear why this wasn't merged years ago. If I'm understanding correctly, I think the original concern was around mentioning other libraries as offering async-compatible connection pooling in the README? I personally am fine with that comment.

@ibraheemdev if you're still out there :laughing: are you able to resolve conflicts and otherwise bring this up-to-date? Would love to get it merged. :smiley:

**Comment by djc** [comment]
@jaymell I forget where but I think I pushed back on adding more examples in the past. I don't really want to be on the hook for maintaining a bunch of examples over time. Maybe the right solution is to move the r2d2 support to a separate crate? We don't maintain integrations for deadpool or bb8, either.

**Comment by jaymell** [comment]
@djc I think that's fine, but in that case we should probably close this and other relevant PRs if alright with you.

**Comment by djc** [comment]
Right, closing this for now.

**Pull request closed without merging**
