### PR TITLE
Add impl FromRedisValue and ToRedisArgs for Arc<str> and Rc<str>

### PR DESCRIPTION
**Pull request by TaQuanMinhLong**

### CODE REVIEW

**Comment by nihohit** [comment]
why don't the existing macros for Arc tackle this?

**Comment by TaQuanMinhLong** [comment]
I think `str` itself does not implement ToRedisArgs and FromRedisValue

**Comment by nihohit** [comment]
Hi, sorry for delaying this review.
Can you please add tests, and Box<str> implementation?

**Comment by TaQuanMinhLong** [comment]
I think I'll close this PR, since there's no way to get the borrowed type from Redis value, so for containers as Rc, Arc, Box, converting into Container<str> would cause more performance overhead comparing to Container<String> (I did research and do some benchmarks myself)

https://www.reddit.com/r/rust/comments/18v8fhg/an_investigation_of_the_performance_of_arcstr_vs/

Regarding ToRedisValue trait, we can just get the ref from Container<String> and it just works anyway

I apologize for my short-sightedness and wasting your time

**Comment by nihohit** [comment]
no worries, thanks for the effort :)

**Pull request closed without merging**
