### PR TITLE
feat: add SMISMEMBER command

### PR DESCRIPTION
**Pull request by Zacaria**
Hello

I have just found that the command SMISMEMBERS is missing from the lib.

I think it can be great for checking presence of multiple members with one network connection.

As I didn't found a Contributing section, I'm naively proposing this change.

Please do not hesitate to tell me what changes are needed along with my initial commit.

Please note that SMISMEMBERS appears at redis version 6.2.0

### CODE REVIEW

**Comment by nihohit** [comment]
thanks for the addition!
can you please add a test?

**Comment by nihohit** [comment]
Well, if the tests before the JSON module tests passed, that's good enough. If you want to be able to run all tests, you'll need to build the JSON module library - see https://github.com/redis-rs/redis-rs/blob/main/README.md#development.

Please fix the lint issues.

**Review by nihohit — APPROVED** [review]

**Comment by FallingSnow** [comment]
Do we close #797 and #832?

**Comment by nihohit** [comment]
> Do we close #797 and #832?

yes, thanks for pointing them out.

**Pull request merged**
