### PR TITLE
add derive Clone and as_map method to InfoDict

### PR DESCRIPTION
**Pull request by danni-m**

### CODE REVIEW

**Comment by danni-m** [comment]
This would also help to fix #631

**Comment by djc** [comment]
I'm fine with the `Clone`. I'm a little on the fence about exposing the implementation detail that we're using a `HashMap` here. What about instead implementing an iterator over (key, value) items?

(Clippy failures can be ignored, see #663.)

**Comment by danni-m** [comment]
@djc first of all, it is possible, and I can do it to move with this PR (Should we implement a new `Iterator` or just expose a slice?). 
My use case is more specific for orchestrating Redis instances where we need a lot more than `get` for Redis info. We preferred not to implement our own parser and use the one provided by the library, but at some point, we were limited by the API. 
My reasoning for exposing Hashmap:
1. Hashmap already provides a lot of useful APIs (like `get`, `len` and `keys` for example)
2. We do use hashmap internally. There's not a lot of value (IMHO) in recreating the same APIs that hashmap already supports.

**Review by djc — APPROVED** [review]

**Review by djc — COMMENTED** [review]
Actually, I think we should probably implement `Deref<Target = &HashMap<String, Value>>` instead of adding `as_map()`. That would also allow us to get rid of some of the simple proxy methods.

**Comment by danni-m** [comment]
@djc removed as_map in favour of Deref

**Comment by djc** [comment]
Thanks! @jaymell want to take a look?

**Comment by jaymell** [comment]
Looks good!

**Pull request merged**
