### PR TITLE
Added missing command for SMISMEMBER

### PR DESCRIPTION
**Pull request by HHogg**
Added a missing fn for the SMISMEMBER cmd

### CODE REVIEW

**Comment by jaymell** [comment]
Hi, thanks for the PR. Can we add a test or two for the command?

**Comment by HHogg** [comment]
Absolutely, happy to. I did have a quick scan of the tests but couldn't find a place where all the commands were being tested. I'll take another look for an appropriate place, if not I'll start something off with a few for the others too.

**Comment by jaymell** [comment]
[test_basic.rs](https://github.com/redis-rs/redis-rs/blob/main/redis/tests/test_basic.rs) is a reasonable place to put them. Thanks!

**Comment by nihohit** [comment]
@HHogg do you think you can add a test?

**Comment by nihohit** [comment]
implemented in https://github.com/redis-rs/redis-rs/pull/1002

**Pull request closed without merging**
