### PR TITLE
Determine the type of a key

### PR DESCRIPTION
**Pull request by bruaba**

### CODE REVIEW

**Comment by bruaba** [comment]
add get type of a key to redis async connection
follow https://github.com/redis-rs/redis-rs/issues/931

**Comment by jaymell** [comment]
Thanks for the PR! 

I personally think I prefer `key_type` instead of `type_key`. What do you think? Could we also add a small test -- in `test_basic.rs` should be fine.

**Comment by bruaba** [comment]
@jaymell 
"I personally think I prefer key_type instead of type_key. What do you think?"
yes you are right it sounds better in English, I was thinking in French hence the type key.

"Could we also add a small test -- in test_basic.rs should be fine."
I added some tests in the test_basic.rs file, hope they will be fine for you.

**Review by jaymell — APPROVED** [review]

**Review by robjtede — APPROVED** [review]

**Comment by jaymell** [comment]
@nihohit LGTM

**Pull request merged**
