### PR TITLE
example how to use redis r2d2 connection pool

### PR DESCRIPTION
**Pull request by nonirosenfeldredis**

### CODE REVIEW

**Comment by djc** [comment]
Documenting this as a docstring on the macro probably doesn't make much sense. Did you check how this appears in the rustdoc output?

**Comment by tasn** [comment]
Looks like a duplicate of #388?

**Comment by djc** [comment]
Yup, it certainly looks like a duplicate.

**Comment by jaymell** [comment]
@djc Shall we close this as well?

**Pull request closed without merging**
